version: '2'

services:
  solr:
    restart: 'unless-stopped'
    image: 'solr5_dev:latest'
    ports:
     - "8983:8983"
    volumes:
      - data:/opt/solr/server/solr/blacklight-core/
volumes:
  data:
